### ISSUE TITLE
 panic: interface conversion: ast.Expr is *ast.SelectorExpr, not *ast.Ident

### ISSUE THREAD

**Issue by hawkingrei** [fatanugraha/noloopclosure#2]
```
[2022-08-16T10:29:15.362Z] Use --sandbox_debug to see verbose messages from the sandbox

[2022-08-16T10:29:15.362Z] compilepkg: panic: interface conversion: ast.Expr is *ast.SelectorExpr, not *ast.Ident

[2022-08-16T10:29:15.362Z] 

[2022-08-16T10:29:15.362Z] goroutine 191 [running]:

[2022-08-16T10:29:15.362Z] github.com/fatanugraha/noloopclosure.getForStmtLoopVars(...)

[2022-08-16T10:29:15.362Z] 	external/com_github_fatanugraha_noloopclosure/noloopclosure.go:82

[2022-08-16T10:29:15.362Z] github.com/fatanugraha/noloopclosure.run.func1({0xd043f0?, 0xc000eff580?})

[2022-08-16T10:29:15.362Z] 	external/com_github_fatanugraha_noloopclosure/noloopclosure.go:34 +0x38b

[2022-08-16T10:29:15.362Z] golang.org/x/tools/go/ast/inspector.(*Inspector).Preorder(0xc0005ba288, {0xc0000bacd8?, 0x2?, 0xc001a5e000?}, 0xc000ebbcc8)

[2022-08-16T10:29:15.362Z] 	external/org_golang_x_tools/go/ast/inspector/inspector.go:77 +0x9a

[2022-08-16T10:29:15.362Z] github.com/fatanugraha/noloopclosure.run(0xc0002081a0)

[2022-08-16T10:29:15.362Z] 	external/com_github_fatanugraha_noloopclosure/noloopclosure.go:26 +0xa5

[2022-08-16T10:29:15.362Z] github.com/pingcap/tidb/build/linter/util.SkipAnalyzer.func1(0xc0002080d0)

[2022-08-16T10:29:15.362Z] 	build/linter/util/util.go:139 +0x11b

[2022-08-16T10:29:15.362Z] main.(*action).execOnce(0xc000e35200)

[2022-08-16T10:29:15.362Z] 	external/io_bazel_rules_go/go/tools/builders/nogo_main.go:301 +0x817

[2022-08-16T10:29:15.362Z] sync.(*Once).doSlow(0x0?, 0x0?)

[2022-08-16T10:29:15.362Z] 	GOROOT/src/sync/once.go:68 +0xc2

[2022-08-16T10:29:15.362Z] sync.(*Once).Do(...)

[2022-08-16T10:29:15.362Z] 	GOROOT/src/sync/once.go:59

[2022-08-16T10:29:15.362Z] main.(*action).exec(0x0?)

[2022-08-16T10:29:15.362Z] 	external/io_bazel_rules_go/go/tools/builders/nogo_main.go:245 +0x3d

[2022-08-16T10:29:15.362Z] main.execAll.func1(0x0?)

[2022-08-16T10:29:15.362Z] 	external/io_bazel_rules_go/go/tools/builders/nogo_main.go:239 +0x54

[2022-08-16T10:29:15.362Z] created by main.execAll

[2022-08-16T10:29:15.362Z] 	external/io_bazel_rules_go/go/tools/builders/nogo_main.go:237 +0x47
```

we find the problem in the https://github.com/pingcap/tidb/pull/37153

**Comment by fatanugraha** [comment]
Thanks for the report, working on the fix right now.

**Comment by fatanugraha** [comment]
@hawkingrei Feel free to re-open the issue if the you see any panic in the latest version. Thanks!
